# fly.toml file generated for phoenix-live-editable on 2022-05-31T07:03:04-07:00
# 
# 2022 May 31 Tue 
# - supposed to be live on phoenix-live-editable.fly.dev
# - this configuration does not work 
# - fly seems to only listen on ports 80 and 443
# - it's running on a VPS at http://173.255.255.44:8080

app = "phoenix-live-editable"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 8080

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# [[services]]
#   http_checks = []
#   internal_port = 8081
#   processes = ["app"]
#   protocol = "tcp"
#   script_checks = []
#
#   [[services.ports]]
#     handlers = ["http"]
#     port = 8081
#
# [[services]]
#   http_checks = []
#   internal_port = 8082
#   processes = ["app"]
#   protocol = "tcp"
#   script_checks = []
#
#   [[services.ports]]
#     handlers = ["http"]
#     port = 8082
#
